require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/leaderboard_categories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # LeaderboardCategory. As you add validations to LeaderboardCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LeaderboardCategory.create! valid_attributes
      get leaderboard_categories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      leaderboard_category = LeaderboardCategory.create! valid_attributes
      get leaderboard_category_url(leaderboard_category)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_leaderboard_category_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      leaderboard_category = LeaderboardCategory.create! valid_attributes
      get edit_leaderboard_category_url(leaderboard_category)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LeaderboardCategory" do
        expect {
          post leaderboard_categories_url, params: { leaderboard_category: valid_attributes }
        }.to change(LeaderboardCategory, :count).by(1)
      end

      it "redirects to the created leaderboard_category" do
        post leaderboard_categories_url, params: { leaderboard_category: valid_attributes }
        expect(response).to redirect_to(leaderboard_category_url(LeaderboardCategory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LeaderboardCategory" do
        expect {
          post leaderboard_categories_url, params: { leaderboard_category: invalid_attributes }
        }.to change(LeaderboardCategory, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post leaderboard_categories_url, params: { leaderboard_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested leaderboard_category" do
        leaderboard_category = LeaderboardCategory.create! valid_attributes
        patch leaderboard_category_url(leaderboard_category), params: { leaderboard_category: new_attributes }
        leaderboard_category.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the leaderboard_category" do
        leaderboard_category = LeaderboardCategory.create! valid_attributes
        patch leaderboard_category_url(leaderboard_category), params: { leaderboard_category: new_attributes }
        leaderboard_category.reload
        expect(response).to redirect_to(leaderboard_category_url(leaderboard_category))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        leaderboard_category = LeaderboardCategory.create! valid_attributes
        patch leaderboard_category_url(leaderboard_category), params: { leaderboard_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested leaderboard_category" do
      leaderboard_category = LeaderboardCategory.create! valid_attributes
      expect {
        delete leaderboard_category_url(leaderboard_category)
      }.to change(LeaderboardCategory, :count).by(-1)
    end

    it "redirects to the leaderboard_categories list" do
      leaderboard_category = LeaderboardCategory.create! valid_attributes
      delete leaderboard_category_url(leaderboard_category)
      expect(response).to redirect_to(leaderboard_categories_url)
    end
  end
end
