env:
  RUBY_VERSION: 3.1.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password

name: Rails tests
on: [push, pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }} 
          HOST_URL: http://localhost:3000
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create database
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
          rails assets:precompile
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Run tests
        run: bundler exec rspec .
      - name: Run brakeman
        run: bundler exec brakeman -o brakeman.txt --no-exit-on-warn
        continue-on-error: true
      - name: Run rubocop
        run: bundler exec rubocop --out rubocop.txt --fail-level error
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
      - name: Upload rubocop report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: rubocop-report.txt
          path: rubocop.txt
      - name: Upload brakeman report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: brakeman-report.txt
          path: brakeman.txt


